name: kai_less
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.1
  dio: ^5.2.1
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.8
  equatable: ^2.0.3
  flutter_markdown: ^0.6.6
  url_launcher: ^6.3.0
  eva_icons_flutter: ^3.0.2
  flutter_bloc: ^7.3.0
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  day_night_switcher: ^0.2.0+1
  intl: ^0.17.0
  flutter_keyboard_visibility: ^5.0.3
  fluttericon: ^2.0.0
  package_info: ^2.0.2
  salomon_bottom_bar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true